import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Generates and downloads a clean, professional PDF report for MedicoBridge.
 *
 * @param {Object} options
 * @param {string} options.title - Report title (e.g., "Doctor Patients Blood Group Report")
 * @param {string} options.selectedBloodGroup - Selected filter (e.g., "B+" or "All Blood Groups")
 * @param {string} options.generatedBy - Who generated the report (e.g., "Dr. Ayisha Shalba (Doctor)" or "Hospital Admin")
 * @param {Array<{header: string, dataKey: string}>} options.columns - Table column definitions
 * @param {Array<Object>} options.data - Filtered rows to include in the report table
 * @param {Object} [options.activeFilters] - Optional extra active filter metadata
 */
export function generateBloodGroupReport({
  title = "Blood Group Report",
  selectedBloodGroup = "All Blood Groups",
  generatedBy = "Authorized User",
  columns = [],
  data = [],
  activeFilters = {},
}) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Colors
  const primaryColor = [13, 148, 136]; // Teal #0d9488
  const darkTextColor = [15, 23, 42]; // #0f172a
  const mutedTextColor = [100, 116, 139]; // #64748b

  // 1. BRAND HEADER
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 26, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("MEDICOBRIDGE", 14, 15);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Healthcare Management Platform", 14, 21);

  // Document Title
  doc.setTextColor(...darkTextColor);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(title, 14, 38);

  // Metadata Block
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...mutedTextColor);

  const nowStr = new Date().toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });

  doc.text(`Selected Blood Group: ${selectedBloodGroup || "All Blood Groups"}`, 14, 46);
  doc.text(`Generated Date/Time: ${nowStr}`, 14, 52);
  doc.text(`Generated By: ${generatedBy}`, 14, 58);

  // Extra filter summary if provided
  let startY = 66;
  const extraFilterKeys = Object.keys(activeFilters).filter(
    (k) => activeFilters[k] && activeFilters[k] !== "All" && activeFilters[k] !== "All Statuses" && activeFilters[k] !== "All Wards"
  );

  if (extraFilterKeys.length > 0) {
    const filterSummary = extraFilterKeys
      .map((k) => `${k}: ${activeFilters[k]}`)
      .join(" | ");
    doc.text(`Active Filters: ${filterSummary}`, 14, startY);
    startY += 8;
  }

  doc.text(`Total Matching Records: ${data.length}`, 14, startY);
  startY += 6;

  // Horizontal divider
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, startY, pageWidth - 14, startY);
  startY += 6;

  // Table Data Formatting
  const tableHeaders = columns.map((col) => col.header);
  const tableRows = data.map((row) =>
    columns.map((col) => {
      const val = row[col.dataKey];
      if (val === undefined || val === null || val === "") return "Not Provided";
      return String(val);
    })
  );

  // Render Table
  autoTable(doc, {
    startY: startY,
    head: [tableHeaders],
    body: tableRows,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 9,
      textColor: darkTextColor,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (dataArg) => {
      // Footer page numbering
      const pageCount = doc.internal.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(...mutedTextColor);
      doc.text(
        `Page ${dataArg.pageNumber} of ${pageCount} - MedicoBridge Emergency Reference Report`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: "center" }
      );
    },
  });

  // Save/Download PDF
  const bgSanitized = (selectedBloodGroup || "all").replace(/[^a-zA-Z0-9]/g, "_");
  const filename = `MedicoBridge_BloodGroup_Report_${bgSanitized}_${Date.now()}.pdf`;
  doc.save(filename);
}
